stages:
  parse_corpus:
    cmd: python src/parse_corpus.py
    deps:
      - data/raw/ru-fr_interference
      - src/parse_corpus.py
    outs:
      - data/parsed/phonemes.csv

  extract_acoustics:
      cmd: python src/extract_acoustics.py
      deps:
        - data/parsed/phonemes.csv
        - src/extract_acoustics.py
      params:
        - params.yaml:
            - acoustics
      outs:
        - data/features/features_acoustic.csv

  # extract_neural_whisper and extract_neural_xlsr were run on Kaggle (GPU required)
  # outputs tracked manually via dvc add
  
  normalise:
    cmd: python src/normalise.py
    deps:
      - data/features/features_acoustic.csv
      - data/features/features_whisper.npz
      - data/features/features_xlsr.npz
      - src/normalise.py
      - data/features/features_whisper_layer4.npz
      - data/features/features_xlsr_layer3.npz
    params:
      - params.yaml:
          - normalise
    outs:
      - data/features/features_acoustic_norm.csv
      - data/features/features_whisper_pca.npz
      - data/features/features_xlsr_pca.npz
      - data/features/features_whisper_layer4_pca.npz
      - data/features/features_xlsr_layer3_pca.npz