stages:
  parse_corpus:
    cmd: python src/parse_corpus.py
    deps:
      - data/raw/ru-fr_interference
      - src/parse_corpus.py
    params:
      - params.yaml:
          - parse
    outs:
      - data/parsed/phonemes.csv

  extract_acoustics:
      cmd: python src/extract_acoustics.py
      deps:
        - data/parsed/phonemes.csv
        - src/extract_acoustics.py
      params:
        - params.yaml:
            - acoustics
      outs:
        - data/features/features_acoustic.csv