acoustics:
  max_formant_female: 5000
  max_formant_male: 4500
  n_formants: 5

whisper:
  model: "openai/whisper-medium"
  layer: 20

xlsr:
  model: "facebook/wav2vec2-large-xlsr-53"
  layer: 10

normalise:
  pca_dims_viz: 2
  pca_dims_clustering: 50

tests_inter_distances:
  n_boot: 2000
  vowels: ["a", "e", "i", "o", "u", "y", "ø", "ɛ", "ɑ", "ə"]
  pairs:
    - ["i", "u"]
    - ["e", "o"]
    - ["a", "u"]
    - ["e", "ɛ"]
    - ["o", "u"]
    - ["a", "ɑ"]
    - ["i", "y"]
    - ["e", "ø"]